Adding wxPython bindings for wxWebKit.
git-svn-id: http://svn.webkit.org/repository/webkit/branches/wx-port-alpha@23896 268f45cc-cd09-0410-ab3c-d52691b4dbfc

diff --git a/trunk/WebKitTools/Scripts/build-wxwebkit b/trunk/WebKitTools/Scripts/build-wxwebkit
--- a/trunk/WebKitTools/Scripts/build-wxwebkit
+++ b/trunk/WebKitTools/Scripts/build-wxwebkit
@@ -9,8 +9,12 @@ set -o errexit
 WK_ROOT=`pwd`/../..
 WK_ROOTDIR=$WK_ROOT
 export WXWEBKIT=1
-WEBKITOUTPUTDIR=`perl -e "use webkitdirs; print baseProductDir()"`
+if [ -z $WEBKITOUTPUTDIR ]; then
+    WEBKITOUTPUTDIR=`perl -e "use webkitdirs; print baseProductDir()"`
+fi
+
 WINDEPS="pthreads/lib/pthreadVC2.dll icu/bin/icuuc34.dll icu/bin/icudt34.dll libcurl/*.dll sqlite3/sqlite3.dll"
+
 # TODO: check that we are running from the root of the source tree...
 
 # cygpath will bork if the dir doesn't exist...
@@ -70,6 +74,7 @@ do_prep=0
 do_extras=0
 do_build=0
 do_clean=0
+do_install=0
 use_wxgc=0
 wxdebug=0
 wxpython=0
@@ -87,9 +92,23 @@ for flag in $*; do
     wxgc)   use_wxgc=1                                     ;;
     wxdebug) wxdebug=1                                     ;;
     wxpython) wxpython=1                                   ;;
+    wxpython-install) wxpython_install=1                   ;;
     *)      export $flag ;; #other_args='$other_args "$flag"'               ;;
     esac
 done
+
+
+SWIG=`which swig`
+
+if [ $wxpython == 1 ]; then
+    # Run swig so that we can spit out an error if it doesn't exist.
+
+    if [ ! -f "$SWIG" ]; then
+        echo "ERROR: Cannot find SWIG. Make sure that SWIG 1.3.29 is located on your path.";
+        exit 1;
+    fi
+fi 
+
 
 #----------------------------------------------------------------------
 
@@ -142,6 +161,11 @@ else
         bakefile -f gnu browser.bkl
         bakefile -f msvc browser.bkl
         bakefile -f msvs2005prj browser.bkl
+        
+        cd $WK_ROOT/WebKit/wx/bindings/python
+        bakefile -f gnu wxwebkit-py.bkl
+        bakefile -f msvc wxwebkit-py.bkl
+        bakefile -f msvs2005prj wxwebkit-py.bkl
     
         # we need to do this because Bakefile doesn't know which
         # platform it's running on with GNU format, and so it defaults
@@ -200,15 +224,36 @@ if [ $do_build == 1 -o $do_clean == 1 ]; then
         WX_EXT=h
         wxdebug=1
     fi
+    
+    PLATFORM_OS="win"
+    if [ "${OSTYPE:0:6}" == "darwin" ]; then
+        PLATFORM_OS="mac"
+    else
+        PLATFORM_OS="linux"
+    fi
 
     WINDEPS="$WINDEPS $WXWIN/lib/vc_dll/wxmsw28u${WX_EXT}_core_vc.dll $WXWIN/lib/vc_dll/wxbase28u${WX_EXT}_vc.dll"
     
-    do_make $WK_ROOT/JavaScriptCore      "-DBUILDING_WX__=1 $WXGC_DEFINE" WX_DEBUG=$wxdebug WEBKIT_ROOT=$WK_ROOTDIR $other_args 
-    do_make $WK_ROOT/WebCore/Projects/wx "-DBUILDING_WX__=1 $WXGC_DEFINE" WX_DEBUG=$wxdebug WEBKIT_ROOT=$WK_ROOTDIR $other_args
-    do_make $WK_ROOT/WebKit/wx "-DBUILDING_WX__=1 $WXGC_DEFINE" WX_DEBUG=$wxdebug WEBKIT_ROOT=$WK_ROOTDIR $other_args 
-    do_make $WK_ROOT/WebKitTools/wxBrowser  "-DBUILDING_WX__=1 $WXGC_DEFINE" WX_DEBUG=$wxdebug WEBKIT_ROOT=$WK_ROOTDIR $other_args 
+    do_make $WK_ROOT/JavaScriptCore      "-DBUILDING_WX__=1 $WXGC_DEFINE" WX_DEBUG=$wxdebug WEBKIT_ROOT=$WK_ROOTDIR PLATFORM_OS=$PLATFORM_OS $other_args 
+    do_make $WK_ROOT/WebCore/Projects/wx "-DBUILDING_WX__=1 $WXGC_DEFINE" WX_DEBUG=$wxdebug WEBKIT_ROOT=$WK_ROOTDIR PLATFORM_OS=$PLATFORM_OS $other_args
+    do_make $WK_ROOT/WebKit/wx "-DBUILDING_WX__=1 -DWXMAKINGDLL=1 $WXGC_DEFINE" WX_DEBUG=$wxdebug WEBKIT_ROOT=$WK_ROOTDIR PLATFORM_OS=$PLATFORM_OS $other_args 
+    do_make $WK_ROOT/WebKitTools/wxBrowser  "-DBUILDING_WX__=1 -DWXUSINGDLL=1 $WXGC_DEFINE" WX_DEBUG=$wxdebug WEBKIT_ROOT=$WK_ROOTDIR PLATFORM_OS=$PLATFORM_OS $other_args 
 
+    
     if [ $do_build == 1 ]; then 
+        if [ $wxpython == 1 ]; then
+            cd $WK_ROOT/WebKit/wx/bindings/python
+            
+            WX_VERSION=`wx-config --version`
+            WX_VERSION="${WX_VERSION:0:3}"
+            SWIG_FLAGS=`python -c "import wx.build.config; import string; print string.join(wx.build.config.swig_args, ' ')"`
+            $SWIG $SWIG_FLAGS -I$WK_ROOT/WebKit/wx -o webview.cpp webview.i
+            
+            PY_INCLUDE=`python -c "import distutils.sysconfig; print distutils.sysconfig.get_python_inc()"`
+            do_make $WK_ROOT/WebKit/wx/bindings/python  "-DBUILDING_WX__=1 -DWXUSINGDLL=1 -I$PY_INCLUDE $WXGC_DEFINE" WX_DEBUG=$wxdebug WEBKIT_ROOT=$WK_ROOTDIR PLATFORM_OS=$PLATFORM_OS $other_args
+        fi
+        
+    
         if [ "${OSTYPE:0:6}" = "darwin" ]; then
             cd  $WEBKITOUTPUTDIR
             mkdir -p wxBrowser.app/Contents/MacOS
